### ISSUE TITLE
sFlow inserted twice on same graph arc?

### ISSUE THREAD

**Issue by sflow** [sflow/vpp-sflow#2]
We need to make sure that enabling sFlow on an interface twice does not insert the sampling node into the graph twice.

**Comment by sflow** [comment]
I believe this issue is addressed by the latest commit, which introduces per-interface data in sflow-main and uses it to gate the enable_disable config changes.
https://github.com/sflow/vpp-sflow/commit/26840826dd6320316bd2f6e500892f6b2c28ef25

**Comment by pimvanpelt** [comment]
Confirmed - we only call `vnet_feature_enable_disable()` at most once now per interface.
