### ISSUE TITLE
global counters

### ISSUE THREAD

**Issue by sflow** [sflow/vpp-sflow#8]
In this commit: https://github.com/sflow/vpp-sflow/commit/86368e28b3d07a6a4dce1af0545f8a7c5b592ade 
I experimented with having the worker threads only ever touch their own thread-local counters.  It is then a job for the main thread to accumulate and sync those with named global counters, such as SFLOW_ERROR_PROCESSED, SFLOW_ERROR_SAMPLED and SFLOW_ERROR_DROPPED.

While this adds a step to the main thread's polling loop it does look like it might reduce the cycles that the worker thread will consume.  And since the main thread will only get around to accumulating/syncing the global counters every millisecond or so,  it seems like it might save cycles overall.

At this stage we don't actually use any of those global counters within the program.  Not even to satisfy the "show sflow" output.  Does that mean we should take them out altogether and not bother with the extra work in the main polling loop?  I'm not sure.  We might find this mechanism helpful later.  It would make it inexpensive for us to add several more counters in the worker threads, and still view them easily.  And as we add drop-monitoring, bidirectional-sampling and per-interface sampling-rates then we might well think of more things to count.

**Comment by pimvanpelt** [comment]
I think we should keep them.

`vppctl show err` shows these, if operators are interested to know if and how many samples were taken, and how many PSAMPLE messages were sent, for example:

```
   Count                  Node                              Reason               Severity 
    178863               sflow                        sflow PSAMPLE sent           error  
 291780096               sflow                     sflow packets processed         error  
    261758               sflow                      sflow packets sampled          error  
    172887               sflow                      sflow packets dropped          error  
 446190168             l2-output                      L2 output packets            error  
 446190168              l2-input                       L2 input packets            error  
        80     TenGigabitEthernet3/0/3-tx     Tx packet drops (dpdk tx failure)    error  
 420959744               sflow                     sflow packets processed         error  
    378037               sflow                      sflow packets sampled          error  
    288045               sflow                      sflow packets dropped          error  
 420959744             l2-output                      L2 output packets            error  
 420959744              l2-input                       L2 input packets            error  
```

**Comment by sflow** [comment]
OK,  that makes sense.  I actually quite like that the numbers we need to conform to the sFlow spec are computed separately,  so we won't disturb them inadvertently if we rearrange these error_counters down the line.

Of course I'm now itching to know how many cycles/pkt we just shaved off the worker-thread fast-path?

A question about that: are you compiling with SFLOW_LOG_CYCLES and using the SFLOW_ERROR_CYCLES counter when you do the performance tests,  or are you getting your numbers from somewhere else?   In other words,  can we just take out the SFLOW_LOG_CYCLES code?  If we don't need it then it's clutter.

**Comment by pimvanpelt** [comment]
Some tests (v5-counters is the experiment, v5 is baseline)
```
pim@hvn6-lab:~/sflow-2$ grep 'sflow' v5-1000-runtime.txt 
sflow-process-samples           any wait                 0               0           27877          6.31e4            0.00
sflow                            active            1139577       291731712               0          1.33e1          256.00
sflow                            active            1644108       420891648               0          1.28e1          256.00

pim@hvn6-lab:~/sflow-2$ grep 'sflow' v5-counters-1000-runtime.txt 
sflow-process-samples          "any wait"                0               0           26694          1.81e5            0.00
sflow                            active            1148834       294101504               0          1.09e1          256.00
sflow                            active            1676380       429153280               0          1.01e1          256.00
```

```
pim@hvn6-lab:~/sflow-2$ grep 'vector rates' v5-1000-runtime.txt  | grep -v in\ 0
  vector rates in 1.0852e7, out 1.0852e7, drop 0.0000e0, punt 0.0000e0
  vector rates in 9.7216e6, out 9.7216e6, drop 0.0000e0, punt 0.0000e0
  vector rates in 1.4866e7, out 1.4866e7, drop 0.0000e0, punt 0.0000e0
  vector rates in 1.4026e7, out 1.4026e7, drop 0.0000e0, punt 0.0000e0

pim@hvn6-lab:~/sflow-2$ grep 'vector rates' v5-counters-1000-runtime.txt  | grep -v in\ 0
  vector rates in 1.0968e7, out 1.0968e7, drop 0.0000e0, punt 0.0000e0
  vector rates in 9.8002e6, out 9.8002e6, drop 0.0000e0, punt 0.0000e0
  vector rates in 1.4799e7, out 1.4799e7, drop 0.0000e0, punt 0.0000e0
  vector rates in 1.4301e7, out 1.4301e7, drop 0.0000e0, punt 0.0000e0
```

experiment progresses quite markedly from 9.72Mpps -> 9.80Mpps for L3 and 14.02Mpps -> 14.30Mpps for L2XC.

**Comment by sflow** [comment]
Looks good.  Thank you for running the numbers.  I tagged a new release.  I'll close this issue now.

**Comment by pimvanpelt** [comment]
One note - although this speeds up the dataplane path, it does introduce a functional regression. We lost one perhaps desirable property when debugging: all counters are now global in main, and none remain in worker-local context.

Before, we would see each thread as it counted packets and samples and drops in thread local counters.
```
pim@hvn6-lab:~$ grep sflow sflow-2/v5-acceptance-err.txt 
    764768               sflow                        sflow PSAMPLE sent           error      ## main
 135858864               sflow                     sflow packets processed         error  ## worker 0
   1309273               sflow                      sflow packets sampled          error  
   1111734               sflow                      sflow packets dropped          error  
 135858840               sflow                     sflow packets processed         error  ## worker 1
   1309730               sflow                      sflow packets sampled          error  
   1117251               sflow                      sflow packets dropped          error  
 135858856               sflow                     sflow packets processed         error  ## worker 2
   1323868               sflow                      sflow packets sampled          error  
   1134330               sflow                      sflow packets dropped          error  
 135858856               sflow                     sflow packets processed         error  ## worker 3
   1322556               sflow                      sflow packets sampled          error  
   1137344               sflow                      sflow packets dropped          error  
```

After, we see the summed up packets, samples and drops in main.
```
vpp# show err
   Count                  Node                              Reason               Severity 
3375932647               sflow                     sflow packets processed         error  
3392889484               sflow                      sflow packets sampled          error  
1003138642               sflow                      sflow packets dropped          error  
2389750800               sflow                        sflow PSAMPLE sent           error  
```

If one thread is misbehaving (for example because it bursts samples or drops), we no longer see it.

By the way, since 'sampled' and 'dropped' are only invoked once at least one sample occurs, and 'processed' happens on every vector, I think that we can get most of the way by simply removing 'processed' and keeping the PREDICT_FALSE() around the original counter updaters for pkts_dropped and pkts_sampled.

**Comment by sflow** [comment]
I'll look into the "processed" counter.  Summing deltas on the "pool" counter should add up to the right total.  I must have done it wrong.

Regarding visibility into per-worker behavior,  we could report counters for each worker if that is helpful -  but we can still do it from the main thread.  Is that an option?

Having said that,  I am OK with not breaking those counters out by worker.  The worker code-path is so simple now that it's hard to imagine needing to compare workers to each other,  except perhaps as a debug option that defaults off?

**Comment by pimvanpelt** [comment]
Perhaps a compromise is to add an `sflow counters enable|disable` which will tuck away any counters if disabled, and allow for the CPU time to be spent if the operator asks for it. That way, we'd add one CPU cycle per vector of 256 packets, to check if we need to update the counters or not.

**Comment by pimvanpelt** [comment]
LGTM - the counters now seem correct:
For L2:  642536963              l2-input                       L2 input packets            error  
For L3:  TenGigabitEthernet130/0/0         9      up          9000/0/0/0     rx packets             442178008

So I will expect 442178008+642536963 = 1084714971 in `show err`
